export const PERMISSIONS = [
    "VIEW_CUSTOMERS",
    "EDIT_CUSTOMERS",
    "CREATE_CUSTOMER",

    "VIEW_SUPPLIERS",
    "EDIT_SUPPLIERS",
    "CREATE_SUPPLIER",

    "VIEW_PRODUCTS",
    "EDIT_PRODUCTS",
    "CREATE_PRODUCT",

    "VIEW_ORDERS",
    "EDIT_ORDERS",
    "CREATE_ORDER",
];

export default PERMISSIONS;

